sudo: required

services:
  - docker

before_install:
  - npm install
  - npm run build
  - docker build -t factycznie/factycznie-frontend .

script:
  - npm test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
