sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - npm install
  - npm run build
  - docker build -t factycznie/factycznie-frontend .

script:
  - npm run unit

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
